task/urls.py
from django.urls import path

from task.views import (
    index,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    assign_delete_task,
    mark_unmark_as_done, signup,
)


urlpatterns = [
    path("", index, name="index"),
    path("task-types/", TaskTypeListView.as_view(), name="task-type-list"),
    path(
        "task-types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update"
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete"
    ),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/assign-delete/",
        assign_delete_task,
        name="assign-delete"
    ),
    path(
        "tasks/<int:pk>/mark-unmark/",
        mark_unmark_as_done,
        name="mark-unmark"
    ),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update"
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete"
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete"
    ),
    path("signup/", signup, name="signup"),
]

app_name = "task"

task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task.urls", namespace="task")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from task_manager import settings


class TaskType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = "task type"
        verbose_name_plural = "task types"

    def __str__(self):
        return self.name


class Task(models.Model):
    PRIORITY_CHOICES = [
        ("urgent", "Urgent"),
        ("high", "High"),
        ("medium", "Medium"),
        ("low", "Low"),
    ]

    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateField()
    is_completed = models.BooleanField()
    priority = models.CharField(
        choices=PRIORITY_CHOICES, default="medium", max_length=10
    )
    task_type = models.ForeignKey(
        TaskType, on_delete=models.SET_NULL, related_name="tasks", null=True
    )
    assignees = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="tasks"
    )

    class Meta:
        ordering = ["is_completed", "priority"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("task:task-detail", kwargs={"pk": self.pk})


class Worker(AbstractUser):
    position = models.ForeignKey(
        "Position",
        on_delete=models.CASCADE,
        related_name="workers",
        blank=True,
        null=True
    )

    class Meta:
        ordering = ["position"]
        verbose_name = "worker"
        verbose_name_plural = "workers"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("task:worker-detail", kwargs={"pk": self.pk})


class Position(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

task/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.utils import timezone

from task.models import Worker, Task


class WorkerForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "position",
        )


class SignupForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = Worker
        fields = UserCreationForm.Meta.fields


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"

    deadline = forms.DateField(
        error_messages={
            "invalid": "Enter a valid date in the format: YYYY-MM-DD"
        }
    )

    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    def clean_deadline(self):
        deadline = self.cleaned_data["deadline"]
        if deadline < timezone.localdate():
            raise ValidationError("The deadline cannot be set in the past")

        max_deadline = timezone.localdate() + timezone.timedelta(days=365 * 20)

        if deadline > max_deadline:
            raise ValidationError("The deadline cannot be set more than 20 years into the future")

        return deadline


class NameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name.."})
    )


class WorkerUsernameSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username.."})
    )

task/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic

from task.forms import WorkerForm, TaskForm, NameSearchForm, WorkerUsernameSearchForm, SignupForm
from task.models import TaskType, Task, Position, Worker


@login_required
def index(request: HttpRequest) -> HttpResponse:
    task_types = TaskType.objects.count()
    tasks = Task.objects.count()
    positions = Position.objects.count()
    workers = Worker.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "task_types": task_types,
        "tasks": tasks,
        "positions": positions,
        "workers": workers,
        "num_visits": num_visits + 1,
    }

    return render(request, "task/index.html", context)


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    template_name = "task/task_type_list.html"
    context_object_name = "task_type_list"
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = NameSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        queryset = TaskType.objects.all()

        name = self.request.GET.get("name")

        if name:
            return queryset.filter(name__icontains=name)

        return queryset


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    template_name = "task/task_type_form.html"
    fields = "__all__"
    success_url = reverse_lazy("task:task-type-list")


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    template_name = "task/task_type_form.html"
    fields = "__all__"
    success_url = reverse_lazy("task:task-type-list")


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    success_url = reverse_lazy("task:task-type-list")
    template_name = "task/task_type_confirm_delete.html"


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = NameSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        queryset = Task.objects.all()

        name = self.request.GET.get("name")

        if name:
            return queryset.filter(name__icontains=name)

        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task:task-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm

    def get_success_url(self):
        return reverse_lazy("task:task-detail", args=[self.object.pk])


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task:task-list")


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = NameSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        queryset = Position.objects.all()

        name = self.request.GET.get("name")

        if name:
            return queryset.filter(name__icontains=name)

        return queryset


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task:position-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("task:position-list")


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    queryset = Worker.objects.select_related("position")
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = WorkerUsernameSearchForm(
            initial={"username": username}
        )

        return context

    def get_queryset(self):
        queryset = get_user_model().objects.all()

        username = self.request.GET.get("username")

        if username:
            return queryset.filter(username__icontains=username)

        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        worker = self.get_object()

        context["is_completed"] = Task.objects.filter(
            assignees=worker, is_completed=True
        )
        context["not_completed"] = Task.objects.filter(
            assignees=worker, is_completed=False
        )

        return context


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerForm
    success_url = reverse_lazy("task:worker-list")


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerForm

    def get_success_url(self):
        return reverse_lazy("task:worker-detail", args=[self.object.pk])


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("task:worker-list")


@login_required
def assign_delete_task(request, pk) -> HttpResponse:
    worker = get_user_model().objects.get(id=request.user.id)
    if Task.objects.get(id=pk) in worker.tasks.all():
        worker.tasks.remove(pk)
    else:
        worker.tasks.add(pk)
    return HttpResponseRedirect(reverse("task:task-detail", args=[pk]))


@login_required
def mark_unmark_as_done(request, pk) -> HttpResponse:
    task = Task.objects.get(id=pk)
    if task.is_completed:
        task.is_completed = False
    else:
        task.is_completed = True
    task.save()
    return HttpResponseRedirect(reverse("task:task-detail", args=[pk]))


def signup(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("login"))
    else:
        form = SignupForm()
    return render(request, "task/signup.html", {"form": form})

templates/task/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <style>
    body {
        background-image: url({% static "images/index.png" %});
        background-size: cover;
    }
  </style>
  <div class="jumbotron color">
    <h1 class="display-color align">Welcome to the Task Manager</h1>
    <p class="lead align">Manage your tasks efficiently with Task Manager.</p>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="card color">
        <div class="card-body">
          <h2 class="display-color">Record Counts</h2>
          <ul class="list-group">
            <li class="list-group-item another-color"><strong>Task types:</strong> <span class="text-primary">{{ task_types }}</span></li>
            <li class="list-group-item another-color"><strong>Tasks:</strong> <span class="text-primary">{{ tasks }}</span></li>
            <li class="list-group-item another-color"><strong>Positions:</strong> <span class="text-primary">{{ positions }}</span></li>
            <li class="list-group-item another-color"><strong>Workers:</strong> <span class="text-primary">{{ workers }}</span></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="card color">
        <div class="card-body">
          <h2 class="display-color">Page Visits</h2>
          <p class="card-text">You have visited this page <span class="text-primary">{{ num_visits }}</span> time<span class="text-primary">{{ num_visits|pluralize }}</span>.</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block image %}
  <img src="{% static "images/home_image.png" %}" alt="Image" class="bottom-image">
{% endblock %}

templates/task/position_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <div class="row justify-content-center">
      <div class="col-md-6 form-container text-center">
        {% if user.is_superuser %}
          <h1 class="text-danger">Delete Position?</h1>
          <p><i>All workers with this position will be deleted as well.</i></p>
          <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
              <input type="submit" value="Yes, delete" class="btn btn-danger">
            </div>
            <a href="{% url 'task:position-list' %}" class="btn btn-primary">Cancel</a>
          </form>
        {% else %}
          <h2 class="text-danger">You cannot delete any Positions because you are not an admin!</h2>
          <a href="{% url 'task:position-list' %}" class="btn btn-primary mt-3">Back</a>
        {% endif %}
      </div>
    </div>

{% endblock %}

templates/task/position_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <div class="row justify-content-center">
    <div class="col-md-8 form-container">
      <h1 class="form-title">{{ object|yesno:"Update,Create" }} Position</h1>
      <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Submit" class="btn btn-primary submit-button">
      </form>
      <a href="{% url 'task:position-list' %}" class="btn btn-dark mt-3">Cancel</a>
    </div>
  </div>
{% endblock %}

templates/task/position_list.html
{% extends "base.html" %}

{% block content %}

  <h1>Position List
    <a href="{% url 'task:position-create' %}" class="btn btn-primary link-to-page">Create</a>
  </h1>

  {% include "includes/search_form.html" %}

  {% if position_list %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for position in position_list %}
          <tr>
            <td>{{ position.id }}</td>
            <td>{{ position.name }}</td>
            <td><a href="{% url 'task:position-update' position.id %}">Update</a></td>
            <td>
              <a href="{% url 'task:position-delete' position.id %}" class="delete-color">Delete</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There are no positions yet.</p>
  {% endif %}
{% endblock %}

templates/task/signup.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block content %}
  <style>
    body {
      background-image: url({% static "images/sign_up.png" %});
      background-size: cover;
    }
  </style>

  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6 login-container">
        <h1 class="text-center">Sign Up</h1>

        {% if form.errors %}
          <p class="error-message">There was an error with your submission. Please correct the errors below.</p>
        {% endif %}

        <form method="post" action="{% url 'task:signup' %}" novalidate>
          {% csrf_token %}
          {{ form|crispy }}

          <div class="text-center mt-3">
            <button type="submit" class="btn btn-primary">Sign Up</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/task/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <div class="row justify-content-center">
      <div class="col-md-6 form-container text-center">
        {% if user.is_superuser %}
          <h1 class="text-danger">Delete Task?</h1>
          <p>Are you sure you want to delete this task?</p>
          <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
              <input type="submit" value="Yes, delete" class="btn btn-danger">
            </div>
            <a href="{{ task.get_absolute_url }}" class="btn btn-primary">Cancel</a>
          </form>
        {% else %}
          <h2 class="text-danger">You cannot delete any Tasks because you are not an admin!</h2>
          <a href="{{ task.get_absolute_url }}" class="btn btn-primary mt-3">Back</a>
        {% endif %}
      </div>
    </div>

{% endblock %}

templates/task/task_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <style>
    body {
        background-image: url({% static "images/bg_image.png" %});
        background-size: cover;
    }
  </style>

  <div class="header">
    <h2>{{ task.name }}</h2>
    <div>
      <a href="{% url 'task:task-delete' task.id %}" class="btn btn-danger link-to-page">Delete</a>
      <a href="{% url 'task:task-update' task.id %}" class="btn btn-secondary link-to-page">Update</a>
    </div>
  </div>

  <div class="task-details">
    <p><strong>Task Type:</strong> {{ task.task_type.name }}</p>
    <p><strong>Description:</strong> {{ task.description }}</p>
  </div>

  <div class="assignee-section">
    <h2>Assignees</h2>
    <div>
      {% if user in task.assignees.all %}
        <a href="{% url 'task:assign-delete' task.id %}" class="btn btn-danger assignee-action">Delete me from this task</a>
      {% else %}
        <a href="{% url 'task:assign-delete' task.id %}" class="btn btn-success assignee-action">Assign me to this task</a>
      {% endif %}

      {% if task.is_completed %}
        <a href="{% url 'task:mark-unmark' task.id %}" class="btn btn-danger">Unmark as done</a>
      {% else %}
        <a href="{% url 'task:mark-unmark' task.id %}" class="btn btn-success">Mark as done</a>
      {% endif %}
    </div>
  </div>

  <hr>

  <ul>
    {% for assignee in task.assignees.all %}
      <li class="assignee-item">{{ assignee.username }} ({{ assignee.first_name }} {{ assignee.last_name }})</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/task/task_list.html
{% extends "base.html" %}

{% block content %}

  <h1>Task List
    <a href="{% url 'task:task-create' %}" class="btn btn-primary link-to-page">Create</a>
  </h1>

  {% include "includes/search_form.html" %}

  {% if task_list %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Deadline</th>
          <th>Is Completed</th>
          <th>Priority</th>
        </tr>
      </thead>
      <tbody>
        {% for task in task_list %}
          <tr>
            <td>{{ task.id }}</td>
            <td><a href="{{ task.get_absolute_url }}">{{ task.name }}</a></td>
            <td>{{ task.deadline }}</td>
            <td>{{ task.is_completed }}</td>
            <td>{{ task.priority }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There are no tasks yet.</p>
  {% endif %}
{% endblock %}

templates/task/task_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-6 form-container text-center">
      {% if user.is_superuser %}
        <h1 class="text-danger">Delete Task Type?</h1>
        <p>Are you sure you want to delete this task type?</p>
        <form action="" method="post">
          {% csrf_token %}
          <div class="mb-3">
            <input type="submit" value="Yes, delete" class="btn btn-danger">
          </div>
          <a href="{% url 'task:task-type-list' %}" class="btn btn-primary">Cancel</a>
        </form>
      {% else %}
        <h2 class="text-danger">You cannot delete any Task Types because you are not an admin!</h2>
        <a href="{% url 'task:task-type-list' %}" class="btn btn-primary mt-3">Back</a>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/task/task_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <div class="row justify-content-center">
    <div class="col-md-7 form-container">
      <h1 class="form-title">{{ object|yesno:"Update,Create" }} Task Type</h1>
      <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Submit" class="btn btn-primary submit-button">
      </form>
      <a href="{% url 'task:task-type-list' %}" class="btn btn-dark mt-3">Cancel</a>
    </div>
  </div>
{% endblock %}

templates/task/task_type_list.html
{% extends "base.html" %}

{% block content %}

  <h1>Task Type List
    <a href="{% url 'task:task-type-create' %}" class="btn btn-primary link-to-page">Create</a>
  </h1>

  {% include "includes/search_form.html" %}

  {% if task_type_list %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for task_type in task_type_list %}
          <tr>
            <td>{{ task_type.id }}</td>
            <td>{{ task_type.name }}</td>
            <td>
              <a href="{% url 'task:task-type-update' task_type.id %}">Update</a>
            </td>
            <td>
              <a href="{% url 'task:task-type-delete' task_type.id %}" class="delete-color">Delete</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There are no task types yet.</p>
  {% endif %}
{% endblock %}

templates/task/worker_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <div class="row justify-content-center">
    <div class="col-md-6 form-container text-center">
      {% if user.is_superuser %}
        <h1 class="text-danger">Delete Worker?</h1>
        <p>Are you sure you want to delete this worker?</p>
        <form action="" method="post">
          {% csrf_token %}
          <div class="mb-3">
            <input type="submit" value="Yes, delete" class="btn btn-danger">
          </div>
          <a href="{{ worker.get_absolute_url }}" class="btn btn-primary">Cancel</a>
        </form>
      {% else %}
        <h2 class="text-danger">You cannot delete any Workers because you are not an admin!</h2>
        <a href="{{ worker.get_absolute_url }}" class="btn btn-primary mt-3">Back</a>
      {% endif %}
    </div>
  </div>

{% endblock %}

templates/task/worker_detail.html
{% extends "base.html" %}

{% block content %}

  <div class="sticky-header form-inline">
    <h2 class="username">Username: {{ worker.username }}</h2>
    <a href="{% url 'task:worker-update' worker.id %}" class="btn btn-secondary ml-5">Update</a>
    <a href="{% url 'task:worker-delete' worker.id %}" class="btn btn-danger ml-2">Delete</a>
  </div>

  <div class="content">
    <p><strong>First Name:</strong> {{ worker.first_name }}</p>
    <p><strong>Last Name:</strong> {{ worker.last_name }}</p>
    <p><strong>Email:</strong> {{ worker.email }}</p>
    <p><strong>Position:</strong> {{ worker.position }}</p>
    <p><strong>Is Staff:</strong> {{ worker.is_staff }}</p>
    <p><strong>Date Joined:</strong> {{ worker.date_joined }}</p>

    <div class="ml-3">
      <h2>Not Completed Tasks</h2>
      {% for task in not_completed %}
        <hr>
        <p><strong>Name:</strong><a href="{{ task.get_absolute_url }}"> {{ task.name }}</a></p>
        <p><strong>Task Type:</strong> {{ task.task_type.name }}</p>
        <p><strong>Deadline:</strong> {{ task.deadline }}</p>
        <p><strong>Priority:</strong> {{ task.priority }}</p>
        <p class="text-muted"><strong>ID:</strong> {{ task.id }}</p>
      {% empty %}
        <p>There are no not completed tasks!</p>
      {% endfor %}

      <h2>Completed Tasks</h2>
      {% for task in is_completed %}
        <hr>
        <p><strong>Name:</strong><a href="{{ task.get_absolute_url }}"> {{ task.name }}</a></p>
        <p><strong>Task Type:</strong> {{ task.task_type.name }}</p>
        <p><strong>Deadline:</strong> {{ task.deadline }}</p>
        <p><strong>Priority:</strong> {{ task.priority }}</p>
        <p class="text-muted"><strong>ID:</strong> {{ task.id }}</p>
      {% empty %}
        <p>There are no completed tasks!</p>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/task/worker_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <div class="row justify-content-center">
    <div class="col-md-8 form-container">
      <h1 class="form-title">{{ object|yesno:"Update,Create" }} Worker</h1>
      <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Submit" class="btn btn-primary submit-button">
      </form>
      {% if object %}
        <a href="{{ worker.get_absolute_url }}" class="btn btn-dark mt-3">Cancel</a>
      {% else %}
        <a href="{% url 'task:worker-list' %}" class="btn btn-dark mt-3">Cancel</a>
      {% endif %}
    </div>
  </div>
{% endblock %}