task/urls.py
from django.urls import path

from task.views import (
    index,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    assign_delete_task,
    mark_unmark_as_done, signup,
)


urlpatterns = [
    path("", index, name="index"),
    path("task-types/", TaskTypeListView.as_view(), name="task-type-list"),
    path(
        "task-types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update"
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete"
    ),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/assign-delete/",
        assign_delete_task,
        name="assign-delete"
    ),
    path(
        "tasks/<int:pk>/mark-unmark/",
        mark_unmark_as_done,
        name="mark-unmark"
    ),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update"
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete"
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete"
    ),
    path("signup/", signup, name="signup"),
]

app_name = "task"

task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task.urls", namespace="task")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
    {% endif %}

    <li class="page-item disabled">
      <span class="page-link">Page {{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/search_form.html
{% load crispy_forms_filters %}

<form action="" class="form-inline">
  {{ search_form|crispy }}
  <input type="submit" value="🔍" class="btn btn-secondary">
</form>

templates/includes/sidebar.html
<ul class="list-group sidebar-nav sticky-sidebar">
  {% if user.is_authenticated %}
    <li class="list-group-item sidebar-bg-color">
      <span class="font-weight-bold">Username:</span>
      <a href="{{ user.get_absolute_url }}" class="ml-2">{{ user.username }}</a>
    </li>
    <li class="list-group-item sidebar-bg-color mb-3">
      <a href="{% url 'logout' %}" class="btn btn-danger btn-block">Logout</a>
    </li>
  {% else %}
    <li class="list-group-item sidebar-bg-color">
      <a href="{% url 'login' %}" class="btn btn-primary btn-block">Login</a>
    </li>
    <li class="list-group-item sidebar-bg-color mb-3">
      <a href="{% url 'task:signup' %}" class="btn btn-primary btn-block">Sign Up</a>
    </li>
  {% endif %}

  <li class="list-group-item sidebar-bg-color">
    <a href="{% url 'task:index' %}" class="btn btn-info btn-block">Home</a>
  </li>
  <li class="list-group-item sidebar-bg-color">
    <a href="{% url 'task:task-type-list' %}" class="btn btn-info btn-block">All Task Types</a>
  </li>
  <li class="list-group-item sidebar-bg-color">
    <a href="{% url 'task:task-list' %}" class="btn btn-info btn-block">All Tasks</a>
  </li>
  <li class="list-group-item sidebar-bg-color">
    <a href="{% url 'task:position-list' %}" class="btn btn-info btn-block">All Positions</a>
  </li>
  <li class="list-group-item sidebar-bg-color">
    <a href="{% url 'task:worker-list' %}" class="btn btn-info btn-block">All Workers</a>
  </li>
</ul>